=== cboyne/CSI3140/Lab6/15.9/nutrition.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="nutritionFacts">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="productName" type="xs:string"/>
				<xs:element name="servingSize" type="xs:string"/>

				<xs:element name="calories">
					<xs:complexType mixed="true">
						<xs:sequence>

							<xs:element name="fatCalories">
								<xs:complexType mixed="true">
									<xs:sequence>

										<xs:element name="fat">
										    <xs:complexType>
										        <xs:simpleContent>
										            <xs:extension base="xs:positiveInteger">
										                <xs:attribute name="unit" type="xs:string" use="required"/>
										            </xs:extension>
										        </xs:simpleContent>
										    </xs:complexType>
										</xs:element>

										<xs:element name="saturatedFat">
										    <xs:complexType>
										        <xs:simpleContent>
										            <xs:extension base="xs:positiveInteger">
										                <xs:attribute name="unit" type="xs:string" use="required"/>
										            </xs:extension>
										        </xs:simpleContent>
										    </xs:complexType>
										</xs:element>

									</xs:sequence>
									<xs:attribute name="unit" type="xs:string"/>
								</xs:complexType>
							</xs:element>

							<xs:element name="cholesterol">
							    <xs:complexType>
							        <xs:simpleContent>
							            <xs:extension base="xs:positiveInteger">
							                <xs:attribute name="unit" type="xs:string" use="required"/>
							            </xs:extension>
							        </xs:simpleContent>
							    </xs:complexType>
							</xs:element>

							<xs:element name="sodium">
							    <xs:complexType>
							        <xs:simpleContent>
							            <xs:extension base="xs:positiveInteger">
							                <xs:attribute name="unit" type="xs:string" use="required"/>
							            </xs:extension>
							        </xs:simpleContent>
							    </xs:complexType>
							</xs:element>

							<xs:element name="totalCarbohydrates">
							    <xs:complexType>
							        <xs:simpleContent>
							            <xs:extension base="xs:positiveInteger">
							                <xs:attribute name="unit" type="xs:string" use="required"/>
							            </xs:extension>
							        </xs:simpleContent>
							    </xs:complexType>
							</xs:element>

							<xs:element name="fiber">
							    <xs:complexType>
							        <xs:simpleContent>
							            <xs:extension base="xs:positiveInteger">
							                <xs:attribute name="unit" type="xs:string" use="required"/>
							            </xs:extension>
							        </xs:simpleContent>
							    </xs:complexType>
							</xs:element>

							<xs:element name="sugars">
							    <xs:complexType>
							        <xs:simpleContent>
							            <xs:extension base="xs:positiveInteger">
							                <xs:attribute name="unit" type="xs:string" use="required"/>
							            </xs:extension>
							        </xs:simpleContent>
							    </xs:complexType>
							</xs:element>

							<xs:element name="protein">
							    <xs:complexType>
							        <xs:simpleContent>
							            <xs:extension base="xs:positiveInteger">
							                <xs:attribute name="unit" type="xs:string" use="required"/>
							            </xs:extension>
							        </xs:simpleContent>
							    </xs:complexType>
							</xs:element>

						</xs:sequence>
						<xs:attribute name="unit" type="xs:string"/>
					</xs:complexType>
				</xs:element>

			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== cboyne/CSI3140/Lab6/15.9/nutrition.xml
<?xml version="1.0" encoding="UTF-8"?>

<nutritionFacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="nutrition.xsd">
    <productName>Grandma White's Cookies</productName>
    <servingSize>1 package</servingSize>
    <calories unit="calories">
    	260
	    <fatCalories unit="calories">
	    	100
		    <fat unit="grams">11</fat>
		    <saturatedFat unit="grams">2</saturatedFat>
	    </fatCalories>
	    <cholesterol unit="milligrams">5</cholesterol>
	    <sodium unit="milligrams">210</sodium>
	    <totalCarbohydrates unit="grams">26</totalCarbohydrates>
	    <fiber unit="grams">2</fiber>
	    <sugars unit="grams">15</sugars>
	    <protein unit="grams">5</protein>
    </calories>
</nutritionFacts>
